runs:
  using: composite
  steps:
    - uses: easimon/maximize-build-space@master
      with:
        swap-size-mb: 100
        remove-dotnet: 'true'
        remove-android: 'true'
        remove-haskell: 'true'
        remove-codeql: 'true'
        remove-docker-images: 'true'
