runs:
  using: composite
  steps:
    - shell: bash
      run: |
        sudo modprobe zram
        dev=$(sudo zramctl --find --algorithm zstd --size 32G)
        sudo mkswap "$dev"
        sudo swapon --priority 100 "$dev"
