on:
  workflow_dispatch: {}
jobs:
  keys:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/ygg-install
      - name: keys
        id: keys
        run: python scripts/nas/ygg-keys.py
    outputs:
      builder_privatekey: ${{ steps.config.outputs.builder_privatekey }}
      builder_ip: ${{ steps.config.outputs.builder_ip }}
      repo_privatekey: ${{ steps.config.outputs.repo_privatekey }}
      repo_ip: ${{ steps.config.outputs.repo_ip }}
      out_privatekey: ${{ steps.config.outputs.out_privatekey }}
      out_ip: ${{ steps.config.outputs.out_ip }}

  nas_repo:
    needs: keys
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/ygg-install
      - uses: ./.github/actions/ygg-config
        with:
          privatekey: ${{ needs.keys.outputs.repo_privatekey }}
      - run: bash scripts/nas/repo.sh

  nas_out:
    needs: keys
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/ygg-install
      - uses: ./.github/actions/ygg-config
        with:
          privatekey: ${{ needs.keys.outputs.out_privatekey }}
      - run: bash scripts/nas/out.sh
