on:
  workflow_dispatch: {}

jobs:
  nas_repo:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt install nfs-kernel-server
      - uses: ./.github/actions/ygg-install
      - uses: ./.github/actions/ygg-config
        with:
          privatekey: ${{ secrets.repo_privatekey }}
      - run: bash scripts/nas/repo.sh
        env:
          builder: ${{ vars.builder_ip }}

  nas_out:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt install nfs-kernel-server
      - uses: ./.github/actions/ygg-install
      - uses: ./.github/actions/ygg-config
        with:
          privatekey: ${{ secrets.out_privatekey }}
      - run: bash scripts/nas/out.sh
        env:
          builder: ${{ vars.builder_ip }}
