on:
  workflow_dispatch: {}

jobs:
  builder:
    runs-on: ubuntu-24.04
    steps:
      - uses: gmankab/lineage/.github/actions/clean@main
      - uses: actions/checkout@v4
      - run: bash scripts/deps/ubuntu-build.sh
      - uses: ./.github/actions/zram
      - run: bash scripts/builder/test.sh
      - run: bash scripts/builder/prepare.sh
      - run: bash scripts/builder/build.sh
      - run: bash scripts/builder/done.sh
